version: '3.8'

services:
  nestjs-app:
    container_name: api-medicine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: 3306
      SERVER_PORT: ${SERVER_PORT}
